#bridge-file-version: #0
function global_toggle/enchants_allowed
function global_toggle/npcs_allowed
function global_toggle/tnt_disallowed
function global_toggle/harming_allowed
function global_toggle/killstreaks_on
function other/actionbar_dktp