#bridge-file-version: #3
function global_toggle/enchants_disallowed
function global_toggle/npcs_disallowed
function global_toggle/harming_disallowed
function global_toggle/tnt_disallowed
function global_toggle/killstreaks_on
function other/actionbar_dktp